"""Add 4-stock management system to products

Revision ID: 08ee5551824b
Revises: 9a043041c254
Create Date: 2025-06-16 02:08:00.530210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ee5551824b'
down_revision = '9a043041c254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_comptoir', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('stock_ingredients_local', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('stock_ingredients_magasin', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('stock_consommables', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('seuil_min_comptoir', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('seuil_min_ingredients_local', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('seuil_min_ingredients_magasin', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('seuil_min_consommables', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_stock_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('last_stock_update')
        batch_op.drop_column('seuil_min_consommables')
        batch_op.drop_column('seuil_min_ingredients_magasin')
        batch_op.drop_column('seuil_min_ingredients_local')
        batch_op.drop_column('seuil_min_comptoir')
        batch_op.drop_column('stock_consommables')
        batch_op.drop_column('stock_ingredients_magasin')
        batch_op.drop_column('stock_ingredients_local')
        batch_op.drop_column('stock_comptoir')

    # ### end Alembic commands ###
