"""Add units table with predefined packaging units

Revision ID: 47c57c11c39b
Revises: b0803a099910
Create Date: 2025-06-18 03:06:39.864427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c57c11c39b'
down_revision = 'b0803a099910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_unit', sa.String(length=10), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_type', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    # ### end Alembic commands ###
