"""Add unit fields to purchase_items

Revision ID: 7e1c16013b50
Revises: 47c57c11c39b
Create Date: 2025-06-18 03:34:57.540461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e1c16013b50'
down_revision = '47c57c11c39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_quantity', sa.Numeric(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('original_unit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('original_unit_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('stock_location',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('purchase_items_received_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['original_unit_id'], ['id'])
        batch_op.drop_column('received_by_id')
        batch_op.drop_column('received_date')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('subtotal_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('shipping_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('shipping_cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('tax_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('subtotal_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('received_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('purchase_items_received_by_id_fkey'), 'users', ['received_by_id'], ['id'])
        batch_op.alter_column('stock_location',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('original_unit_price')
        batch_op.drop_column('original_unit_id')
        batch_op.drop_column('original_quantity')

    # ### end Alembic commands ###
