"""Align Recipe model with form for product_id

Revision ID: 8e4c7b1f29f6
Revises: 9472c6aa3507
Create Date: 2025-06-13 05:14:11.751275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4c7b1f29f6'
down_revision = '9472c6aa3507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('yield_quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('yield_quantity',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=False)

    # ### end Alembic commands ###
