"""Ajout production_location a Recipe avec server_default

Revision ID: adeaabdabae2
Revises: b1b79fb9c965
Create Date: 2025-06-24 00:14:08.803553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adeaabdabae2'
down_revision = 'b1b79fb9c965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredients')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=True))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_location', sa.String(length=50), server_default='ingredients_magasin', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('production_location')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('payment_date')
        batch_op.drop_column('is_paid')

    op.create_table('recipe_ingredients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_needed', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('recipe_ingredients_product_id_fkey')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('recipe_ingredients_recipe_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recipe_ingredients_pkey'))
    )
    # ### end Alembic commands ###
