"""Add simple payment tracking to purchases

Revision ID: b1b79fb9c965
Revises: 7e1c16013b50
Create Date: 2025-06-19 01:32:51.037535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b79fb9c965'
down_revision = '7e1c16013b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True, default=False))
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('payment_date')
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
