"""Ajout total_stock_value a Product pour PMP

Revision ID: db55e5653df2
Revises: 8aa75d729ef0
Create Date: 2025-06-25 23:15:03.760660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db55e5653df2'
down_revision = '8aa75d729ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_stock_value', sa.Numeric(precision=12, scale=4), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('total_stock_value')

    # ### end Alembic commands ###
